version: '2'
services:
  kapua-sql:
    image: iot/kapua-sql:0.3.1
    restart: always

  kapua-elasticsearch:
    image: iot/elasticsearch:5.4.0
    restart: always
    command:
    - -Ecluster.name=kapua-datastore
    - -Ediscovery.type=single-node
    - -Etransport.host=_site_
    - -Etransport.ping_schedule=-1
    - -Etransport.tcp.connect_timeout=30s

  kapua-broker:
    image: iot/kapua-broker:0.3.1
    restart: always
    links:
      - kapua-sql:db
      - kapua-elasticsearch:es
    environment:
      - commons.db.schema.update=true
      - DB_PORT_3306_TCP_PORT=3306
    ports:
      - "${broker_port1}:1883"
      - "${broker_port2}:61614"

  kapua-console:
    image: iot/kapua-console:0.3.1
    restart: always
    links:
      - kapua-sql:db
      - kapua-elasticsearch:es
      - kapua-broker:broker
    environment:
      - commons.db.schema.update=true
    ports:
      - "${console_port1}:8080"

  kapua-api:
    image: iot/kapua-api:0.3.1
    restart: always
    links:
      - kapua-sql:db
      - kapua-elasticsearch:es
      - kapua-broker:broker
    environment:
      - commons.db.schema.update=true
    ports:
      - "${api_port1}:8080"
