apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-jenkins
spec:
  capacity:
    storage: 30Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-jenkins
  local:
    path: /app/kelu/local-storage/jenkins
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rqcicddev03

